merge fixes for aarch64 into mainline

diff --git a/src/edgemlsdk/Dockerfile b/src/edgemlsdk/Dockerfile
--- a/src/edgemlsdk/Dockerfile
+++ b/src/edgemlsdk/Dockerfile
@@ -1,20 +1,40 @@
 ARG OS
 FROM public.ecr.aws/ubuntu/ubuntu:${OS}
+ARG OS
 ARG PLATFORM
 # Use non-interactive mode to suppress any prompt during installation
 ENV DEBIAN_FRONTEND noninteractive
+
 # Install basic dev libraries
 RUN apt-get update 
 RUN apt-get install build-essential software-properties-common lsb-release git curl libcurl4 libcurl4-openssl-dev \
-    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good  \
+    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev gnupg pkg-config \
     gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl \
     gstreamer1.0-gtk3 gstreamer1.0-qt5 libgstrtspserver-1.0-dev libgirepository1.0-dev libudev-dev libssl-dev --fix-missing -y
-
-
+RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 16FAAD7AF99A65E2
+# build openssl3 if on older system for the AWS IoT library
+RUN if [ "$OS" = "18.04" ]; then \
+    	apt-get install -y wget build-essential zlib1g-dev ca-certificates; \
+    	wget https://github.com/openssl/openssl/releases/download/openssl-3.0.17/openssl-3.0.17.tar.gz; \
+    	tar -xzf openssl-3.0.17.tar.gz;  \
+    	cd openssl-3.0.17; \
+    	./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib; \
+    	make; \
+    	make install; \
+        ldconfig; \ 
+        ls -al /usr/local/ssl; \
+        mkdir -p /usr/local/ssl/certs; \
+        cp /etc/ssl/certs/ca-certificates.crt /usr/local/ssl/certs/; \
+       
+    fi
+ENV LD_LIBRARY_PATH=/usr/local/lib/
+RUN echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
+#RUN /usr/local/ssl/bin/openssl  version
+RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 16FAAD7AF99A65E2
 # Install gcc/g++ 11
 
 RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
-    apt-get update && \
+    apt-get update && \  
     apt install gcc-11 g++-11 -y && \
     rm /usr/bin/gcc && \
     rm /usr/bin/g++ && \
@@ -38,30 +58,64 @@ RUN apt update && \
     apt-get install clang -y
 
 # Install the latest versions of CMake
-RUN apt-get install -y software-properties-common lsb-release && \
-    apt-get clean all && \
-    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
-    apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" && \
-    apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80  6AF7F09730B3F0A4 && \
-    apt-get update && \
-    apt-get install kitware-archive-keyring && \
-    rm /etc/apt/trusted.gpg.d/kitware.gpg && \
-    apt-get update && \
-    apt-get install cmake=3.21.3-0kitware1ubuntu20.04.1 cmake-data=3.21.3-0kitware1ubuntu20.04.1 -y
+RUN if [ "$OS" = "18.04" ]; then \
+        apt-get install -y software-properties-common lsb-release && \
+        apt-get clean all && \
+        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
+        apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" && \
+        apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80  6AF7F09730B3F0A4 && \
+        apt-get update && \
+        apt-get install kitware-archive-keyring && \
+        rm /etc/apt/trusted.gpg.d/kitware.gpg && \
+        apt-get update && \
+        apt-get install cmake=3.21.3-0kitware1ubuntu18.04.1 cmake-data=3.21.3-0kitware1ubuntu18.04.1 -y; \
+    else \
+        apt-get install -y software-properties-common lsb-release && \
+        apt-get clean all && \
+        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
+        apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" && \
+        apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80  6AF7F09730B3F0A4 && \
+        apt-get update && \
+        apt-get install kitware-archive-keyring && \
+        rm /etc/apt/trusted.gpg.d/kitware.gpg && \
+        apt-get update && \
+        apt-get install cmake=3.21.3-0kitware1ubuntu20.04.1 cmake-data=3.21.3-0kitware1ubuntu20.04.1 -y; \
+    fi
 
 # Install specific version of Python
-ARG PYTHON_VERSION
-RUN echo "Python Version = ${PYTHON_VERSION}"
-RUN apt-get install python${PYTHON_VERSION}-dev libpython${PYTHON_VERSION} python${PYTHON_VERSION} python${PYTHON_VERSION}-venv python3-pip -y && \
-    python${PYTHON_VERSION} -m pip install --user --upgrade pip && \
-    python${PYTHON_VERSION} -m pip install --upgrade build
+#ARG PYTHON_VERSION
+#RUN echo "Python Version = ${PYTHON_VERSION}"
+#RUN apt-get install python${PYTHON_VERSION}-dev libpython${PYTHON_VERSION} python${PYTHON_VERSION} python${PYTHON_VERSION}-venv python3-pip -y && \
+#    python${PYTHON_VERSION} -m pip install --user --upgrade pip && \
+#    python${PYTHON_VERSION} -m pip install --upgrade build
+
+RUN wget https://www.python.org/ftp/python/3.9.23/Python-3.9.23.tgz
+RUN tar -xzf Python-3.9.23.tgz
+RUN cd Python-3.9.23 && \
+    ./configure --enable-optimizations --enable-shared && \
+    make -j$(nproc) && \
+    make install && \
+    ldconfig
+
+RUN update-alternatives --install /usr/local/bin/python3 python3 /usr/local/bin/python3.9 1 \
+    && update-alternatives --set python3 /usr/local/bin/python3.9 
+
+ENV PYTHON_EXECUTABLE=/usr/local/bin/python3.9
+ENV Python3_EXECUTABLE=/usr/local/bin/python3.9
+ENV Python3_INCLUDE_DIR=/usr/local/include/python3.9
+ENV Python3_LIBRARY=/usr/local/lib/libpython3.9.so
+RUN find / -name "libpython3.9.so.1.0" -print
+
+RUN pip3 install --upgrade pip setuptools wheel build hatchling
+RUN python3.9 -c "import ssl; print('SSL support:', ssl.OPENSSL_VERSION)" || echo "SSL module not available"
+RUN python3.9 -c "import urllib.request; urllib.request.urlopen('https://pypi.org')" || echo "HTTPS connection failed"
 
 # Conan version 2.1.0 has a bug causing build failure. Github issue: https://github.com/conan-io/conan/issues/15742
 # Installing v.2.0.17 for now. Modify this after bug is resolved
-RUN python${PYTHON_VERSION} -m pip install pyYAML --ignore-installed && \
-    python${PYTHON_VERSION} -m pip install conan==2.0.17 && \
+RUN pip3 install pyYAML && \
+    pip3 install conan && \
     conan profile detect
-
+RUN pip3 install --upgrade pydantic setuptools
 # Coverage Tools
 RUN apt-get install lcov -y
 
@@ -71,23 +125,19 @@ RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-${PLATFORM}.zip" -o awsc
     && unzip awscliv2.zip \
     && ./aws/install
 
-# Coverage Tools
-RUN apt-get install lcov -y
-
 # Install openssl
 # Although Ubuntu 18.04 and 20.04 use openssl 1.1.x, when DDA consumes EdgeML SDK the automated container scan detects multiple CVEs
 # We need to install openssl >= 3.1.1, may as well get the newest version as of writing (3.3.0)
 # Using a mismatched version can lead to seg-fault from some AWS calls, so make sure to distribute and use the same version
-RUN apt-get install checkinstall -y
-RUN mkdir /dependencies
-RUN mkdir /dependencies/debs
+RUN apt-get install checkinstall -y && \
+    mkdir -p /dependencies/debs
 RUN cd /dependencies \
     && git clone https://github.com/openssl/openssl.git \
     && cd openssl \
     && git checkout f84622c7e7f83a9bba30b25898182090801e752d \
     && git submodule update --init --recursive \
-    && ./Configure \
-    && make \
+    && ./Configure --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib no-docs no-tests \
+    && make -j$(nproc)\
     && checkinstall -y \
     && mv /dependencies/openssl/openssl*.deb /dependencies/debs \
     && rm -rf /dependencies/openssl
@@ -115,8 +165,9 @@ RUN cd /dependencies/aws-crt-cpp/crt/s2n \
     && git apply aws-crt-cpp-s2n.diff \
     && mkdir /dependencies/aws-crt-cpp/build \
     && cd /dependencies/aws-crt-cpp/build \
-    && cmake -GNinja -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DUSE_OPENSSL=ON -DBUILD_SHARED_LIBS=ON ../ \
+    && cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DUSE_OPENSSL=ON -DBUILD_SHARED_LIBS=ON ../ \
     && ninja install
+
 
 RUN cd /dependencies \
     && PLATFORM=$(uname -m) \
@@ -126,7 +177,7 @@ RUN cd /dependencies \
     && git submodule update --init --recursive \
     && mkdir build \
     && cd build \
-    && cmake -GNinja -DCMAKE_MODULE_PATH=/usr/lib/$PLATFORM-linux-gnu/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DBUILD_DEPS=OFF -DBUILD_ONLY="s3;sts;secretsmanager;sagemaker-edge;transfer;iot;iot-data" ../ \
+    && cmake -GNinja -DBUILD_TESTING=OFF -DCMAKE_MODULE_PATH=/usr/lib/$PLATFORM-linux-gnu/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DBUILD_DEPS=OFF -DBUILD_ONLY="s3;sts;transfer;iot;iot-data;sagemaker-edge;secretsmanager" ../ \
     && ninja install
 
 # We build this separately as its part of aws-iot-sdk crt, and not in aws-cpp-sdk crt
@@ -137,17 +188,18 @@ RUN cd /dependencies \
      && git submodule update --init --recursive \
      && mkdir build \
      && cd build \
-     && cmake -GNinja -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE="Release" ../ \
+     && cmake -GNinja -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_INSTALL_PREFIX=/usr/ -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=OFF ../ \
      && ninja install
 
 # Install Dependencies for aravis sdk
 RUN apt-get install libxml2-dev libglib2.0-dev libusb-1.0-0-dev gobject-introspection \
-            libgtk-3-dev gtk-doc-tools  xsltproc \
+            libgtk-3-dev libjpeg-dev gtk-doc-tools  xsltproc \
             libgstreamer-plugins-good1.0-dev \
             gettext -y
-
+ENV PKG_CONFIG_PATH = /usr/lib/aarch64-linux-gnu/pkgconfig./usr/lib/aarch64-linux-gnu/pkgconfig
+ 
 # Install meson
-RUN python3 -m pip install meson
+RUN pip3 install meson
 
 # Install aravis sdk release version 0.8
 RUN cd /dependencies \
@@ -155,7 +207,7 @@ RUN cd /dependencies \
     && cd aravis \
     && git checkout 96cea9835ce1535547d8680c8b0be33e97f6cb30 \
     && git submodule update --init --recursive \
-    && meson setup build  \
+    && meson setup build -Dtests=false \
     && cd build \
     && ninja \
     && ninja install
@@ -180,14 +232,24 @@ RUN apt-get install gdb -y
 RUN apt-get install vim -y
 
 # Python Dependencies
+RUN echo "check which python we are using"
+RUN which python3
+RUN which pip3
+RUN pip3 --version
+RUN which pip
+RUN pip --version
+RUN which python3.9
+RUN python3 --version
 RUN apt-get install libcairo2 libcairo2-dev -y
 RUN apt-get remove --autoremove python3-gi -y \
-    && python3.9 -m pip install Cython boto3 awscrt multiprocess conan coverage pylint \
-    && python3.9 -m pip install -U scalene \
-    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 \
-    && update-alternatives --set python3 /usr/bin/python3.9
+    && pip install Cython boto3 awscrt multiprocess conan coverage pylint 
+#RUN pip install scalene 
 
-RUN python3.9 -m pip install pygobject==3.44.1
+RUN pip3 install pygobject==3.44.1
+ENV PYTHON_EXECUTABLE=/usr/local/bin/python3.9
+ENV Python3_EXECUTABLE=/usr/local/bin/python3.9
+ENV Python3_INCLUDE_DIR=/usr/local/include/python3.9
+ENV Python3_LIBRARY=/usr/local/lib/libpython3.9.so
 
 # Install SWIG
 RUN mkdir /swig \
@@ -239,12 +301,22 @@ RUN apt-get install python-dev -y
 # ERROR: cannot verify boostorg.jfrog.io's certificate, issued by 'CN=GeoTrust TLS RSA CA G1,OU=www.digicert.com,O=DigiCert Inc,C=US':
 # Self-signed certificate encountered.
 RUN cd /dependencies && \
-    wget https://cytranet-dal.dl.sourceforge.net/project/boost/boost/1.81.0/boost_1_81_0.tar.gz --no-check-certificate && \
-    tar -xzvf boost_1_81_0.tar.gz && \
-    rm boost_1_81_0.tar.gz && \
-    cd boost_1_81_0 && \
+    wget --no-check-certificate https://github.com/boostorg/boost/releases/download/boost-1.81.0/boost-1.81.0.tar.gz && \
+    tar -xzvf boost-1.81.0.tar.gz && \
+    rm boost-1.81.0.tar.gz && \
+    cd boost-1.81.0 && \
     ./bootstrap.sh && \
     ./b2 install
+
+
+#RUN cd /dependencies && \
+ #   wget --no-check-certificate https://github.com/boostorg/boost/releases/download/boost-1.81.0/boost-1.81.0.tar.gz && \
+    #wget https://cytranet-dal.dl.sourceforge.net/project/boost/boost/1.81.0/boost_1_81_0.tar.gz --no-check-certificate && \
+  #  tar -xzvf boost_1_81_0.tar.gz && \
+   # rm boost-1_81_0.tar.gz && \
+    #cd boost-1_81_0 && \
+    #./bootstrap.sh && \
+    #./b2 install
 RUN apt-get install libnuma-dev -y \
     && rm /usr/bin/python \
     && ln -s /usr/bin/python3.9 /usr/bin/python
@@ -263,12 +335,45 @@ RUN cd /dependencies && \
 COPY patches/edgeml-triton-server.diff /dependencies/server/edgeml-triton-server.diff
 COPY patches/edgeml-triton-core.diff /dependencies/server/edgeml-triton-core.diff
 #b64-dev required for triton metrics
-
 RUN apt-get install libb64-dev -y
 # Apply server patch, internally the server patch applies core patch, build triton.
-RUN cd /dependencies/server && \ 
+RUN echo PATH=$PATH
+RUN export
+# Remove Python 3.6 system packages that pybind11 is finding
+RUN if [ "$OS" = "18.04" ]; then \
+    apt-get remove --purge python python3.6 python3.6-minimal libpython3.6 libpython3.6-minimal libpython3.6-stdlib python3-minimal python3-distutils python3-lib2to3 -y;  \
+    apt-get autoremove -y; \
+    ln -sf /usr/local/bin/python3.9 /usr/bin/python3; \
+    mkdir -p /usr/include/python3.6m;  \ 
+    ln -sf /usr/local/include/python3.9/* /usr/include/python3.6m/; \
+    fi
+
+#RUN echo "=== Python Debug Info ===" && \
+#    python3 --version && \
+#    which python3 && \
+#    ls -la /usr/bin/python* && \
+#    ls -la /usr/include/python* && \
+#    find /usr -name "python*.pc" 2>/dev/null && \
+#    dpkg -l | grep python3 && \
+#    echo "=== Environment Variables ===" && \
+#    env | grep -i python && \
+#    echo "=== End Debug ==="
+RUN    export PYBIND11_FINDPYTHON=ON && \
+    cd /dependencies/server && \ 
     git apply edgeml-triton-server.diff && \
-    python3 build.py --enable-logging  --enable-stats --enable-metrics --enable-cpu-metrics --no-container-build --extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON --extra-core-cmake-arg=CMAKE_POLICY_VERSION_MINIMUM=3.5 --backend python --build-dir=`pwd`/build
+    python3.9 build.py --enable-logging  --enable-stats --enable-metrics --enable-cpu-metrics --no-container-build \
+    --extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON \
+    --extra-core-cmake-arg=PYBIND11_FINDPYTHON=ON \
+    --extra-core-cmake-arg=-DPYBIND11_FINDPYTHON=ON \
+    --extra-core-cmake-arg=CMAKE_POLICY_VERSION_MINIMUM=3.5 \
+    --extra-core-cmake-arg=PYTHON_EXECUTABLE=/usr/local/bin/python3.9 \
+    --extra-core-cmake-arg=-DPYTHON_EXECUTABLE=/usr/local/bin/python3.9 \
+    --extra-core-cmake-arg=PYTHON_INCLUDE_DIR=/usr/local/include/python3.9 \
+    --extra-core-cmake-arg=PYTHON_LIBRARY=/usr/local/lib/libpython3.9.so \
+    --extra-core-cmake-arg=PYTHON_LIBRARIES=/usr/local/lib/libpython3.9.so \ 
+    --extra-core-cmake-arg=-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.9 \
+    --extra-core-cmake-arg=PYBIND11_PYTHON_VERSION=3.9 \
+    --backend python --build-dir=`pwd`/build
 RUN mv /dependencies/server/build/python/install/backends/python /dependencies/server/build/tritonserver/install/backends
 
 RUN cd /dependencies/server/build/opt/ \
@@ -298,6 +403,13 @@ RUN cd /dependencies/debs \
     && chmod +x create_aws_triton_deps_pkg.sh \
     && ./create_aws_triton_deps_pkg.sh
 
+# Install GStreamer packages needed for build
+RUN apt-get update && apt-get install -y \
+    libgstreamer1.0-dev \
+    libgstreamer-plugins-base1.0-dev \
+    libglib2.0-dev \
+    libxml2-dev
+
 # Download other packages
 RUN cd /dependencies/debs \
     && apt-get download libgstreamer1.0-dev \
@@ -306,6 +418,13 @@ RUN cd /dependencies/debs \
     && apt-get download libgstreamer-plugins-base1.0-dev \
     && apt-get download liborc-0.4-0 \
     && apt-get download libstdc++6
+#TODO add if check here, 1.15 for ubuntu 18.04/20.04 and 1.16 for 22.04+
+#RUN wget --no-check-certificate https://github.com/civetweb/civetweb/archive/refs/tags/v1.15.tar.gz \
+#    && tar -xzvf v1.15.tar.gz \
+#    && cd civetweb-1.15 \
+#    && make build \
+#    && make build install \
+#    && ldconfig 
 
 RUN cd src/ \
     && conan build . --build=missing \
@@ -336,13 +455,7 @@ RUN cd src/ \
     && mkdir -p /tars \
     && cd /tars \
     && cp /dependencies/tars/triton_installation_files.tar.gz .
-# cleanup - this only applies to JP4.x
 
-RUN if test -f /usr/bin/python3.6; then \
-        mv /usr/bin/python3.6-bak /usr/bin/python3.6; \
-    else \
-        echo "no python3.6 found to clean up"; \
-    fi
 
 
 RUN apt-get clean
